FROM molecularplayground/node-js

COPY . /src

WORKDIR /src

RUN npm install -g nodemon

# don't run npm install until we have already mounted the working directory
CMD /bin/sh -c "npm install && nodemon -L run start-dev"

EXPOSE 3000
